language: c
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install pkg-config libtool flex autopoint gettext zlib1g-dev libbz2-dev liblzma-dev libselinux1-dev libncursesw5-dev perl libtimedate-perl libio-string-perl
script:
  - autoreconf -f -i && ./configure && make check
